name: moodbot
channels:
  - conda-forge
dependencies:
  - python<=3.11
  - mamba
  - openai
  - keras
  - numpy
  - pillow
  - tensorflow
  - opencv
  - pandas
  - scikit-learn
  - ffmpeg
  - pip
  - pip:
    - --index-url https://pypi.org/simple/
    - protobuf>=5.0,<6.0
    - mcpi
    - mediapipe
    - joblib
    - telepot
    - pillow-heif
